os:
  - linux
  - osx

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install openssl libidn rtmpdump libssh2 c-cares libmetalink libressl nghttp2; fi
before_script:
  - ./buildconf

script: ./configure --enable-debug && make && make test-full

language: c

compiler:
  - clang
  - gcc

notifications:
  email: false
